### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by Gozzim** [Gozzim/mod-FirstLogin-AIO#1]
- [x] Hunter stable slots
- [x] Hunter random pet
- [x] Player Bankslots
- [x] DualSpec
- [x] Add hunter spells option
- [ ] Rework name generation (currently very simple approach)
- [ ] Fill sql files for name generation
- [ ] Add learn all spells option
